export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCESSS';
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL';
export const GET_ALL_POSTS_RESET = 'GET_ALL_POSTS_RESET';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCESSS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const CREATE_POST_RESET = 'CREATE_POST_RESET';