export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCESSS';
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL';
export const GET_ALL_POSTS_RESET = 'GET_ALL_POSTS_RESET';