export const USERLOGIN_REQUEST = 'USERLOGIN_REQUEST';
export const USERLOGIN_SUCCESS = 'USERLOGIN_SUCESSS';
export const USERLOGIN_FAIL = 'USERLOGIN_FAIL';
export const USERLOGIN_RESET = 'USERLOGIN_RESET';